# 阿帕比作者信息建表sql
CREATE TABLE APABI_BOOK_METADATA_AUTHOR(
    ID VARCHAR2(64) PRIMARY KEY,
    METAID VARCHAR2(64),
    AUTHORTYPE VARCHAR2(32),
    NAME VARCHAR2(256),
    TYPE VARCHAR2(64),
    PINYIN VARCHAR2(128),
    ORIGINALNAME VARCHAR2(128),
    APABIAUTHORID VARCHAR2(128),
    NLCAUTHORID VARCHAR2(128),
    PRIORITY VARCHAR2(32),
    NLCMARCIDENTIFIER VARCHAR2(128),
    ADDITION VARCHAR2(512),
    OPERATOR VARCHAR2(128),
    CREATETIME DATE,
    UPDATETIME DATE
);