# 国图marc数据建表sql
create table book.nlc_book_marc(
    NLCMARCID VARCHAR2(64) PRIMARY KEY,
    TITLE VARCHAR2(500),
    AUTHOR VARCHAR2(500),
    PUBLISHER VARCHAR2(255),
    ISBN VARCHAR2(255),
    METAID VARCHAR2(128),
    ISOCONTENT CLOB,
    ISOFILEPATH VARCHAR2(500),
    CREATETIME DATE,
    UPDATETIME DATE
);