# 丛书数据信息建表sql
CREATE TABLE APABI_BOOK_SERIES_DATA(
    ID VARCHAR2(64) PRIMARY KEY,
    NLCMARCIDENTIFIER VARCHAR2(64),
    ISBN VARCHAR2(64),
    METAID VARCHAR2(64),
    RELATIONID VARCHAR2(64),
    TITLE VARCHAR2(512),
    AUTHOR VARCAHR2(128),
    SERIESTITLE VARCAHR2(256),
    PARALLELSERIESTITLE VARCAHR2(256),
    SERIESSUBTITLE VARCAHR2(256),
    SERIESAUTHOR VARCAHR2(256),
    VOLUME VARCAHR2(256),
    VOLUMETITLE VARCAHR2(256),
    VOLUMEID VARCAHR2(256),
    CREATETIME DATE,
    UPDATETIME DATE
);